//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emiplus.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int user_id {
            get {
                return ((int)(this["user_id"]));
            }
            set {
                this["user_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_name {
            get {
                return ((string)(this["user_name"]));
            }
            set {
                this["user_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_lastname {
            get {
                return ((string)(this["user_lastname"]));
            }
            set {
                this["user_lastname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_document {
            get {
                return ((string)(this["user_document"]));
            }
            set {
                this["user_document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user_thumb {
            get {
                return ((string)(this["user_thumb"]));
            }
            set {
                this["user_thumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_email {
            get {
                return ((string)(this["user_email"]));
            }
            set {
                this["user_email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_cell {
            get {
                return ((string)(this["user_cell"]));
            }
            set {
                this["user_cell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int user_level {
            get {
                return ((int)(this["user_level"]));
            }
            set {
                this["user_level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int user_status {
            get {
                return ((int)(this["user_status"]));
            }
            set {
                this["user_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_plan_id {
            get {
                return ((string)(this["user_plan_id"]));
            }
            set {
                this["user_plan_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int user_plan_trial {
            get {
                return ((int)(this["user_plan_trial"]));
            }
            set {
                this["user_plan_trial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int user_plan_status {
            get {
                return ((int)(this["user_plan_status"]));
            }
            set {
                this["user_plan_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int empresa_id {
            get {
                return ((int)(this["empresa_id"]));
            }
            set {
                this["empresa_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_logo {
            get {
                return ((string)(this["empresa_logo"]));
            }
            set {
                this["empresa_logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_razao_social {
            get {
                return ((string)(this["empresa_razao_social"]));
            }
            set {
                this["empresa_razao_social"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_nome_fantasia {
            get {
                return ((string)(this["empresa_nome_fantasia"]));
            }
            set {
                this["empresa_nome_fantasia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_cnpj {
            get {
                return ((string)(this["empresa_cnpj"]));
            }
            set {
                this["empresa_cnpj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_inscricao_estadual {
            get {
                return ((string)(this["empresa_inscricao_estadual"]));
            }
            set {
                this["empresa_inscricao_estadual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_inscricao_municipal {
            get {
                return ((string)(this["empresa_inscricao_municipal"]));
            }
            set {
                this["empresa_inscricao_municipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_telefone {
            get {
                return ((string)(this["empresa_telefone"]));
            }
            set {
                this["empresa_telefone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_rua {
            get {
                return ((string)(this["empresa_rua"]));
            }
            set {
                this["empresa_rua"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_cep {
            get {
                return ((string)(this["empresa_cep"]));
            }
            set {
                this["empresa_cep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_nr {
            get {
                return ((string)(this["empresa_nr"]));
            }
            set {
                this["empresa_nr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_bairro {
            get {
                return ((string)(this["empresa_bairro"]));
            }
            set {
                this["empresa_bairro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string empresa_estado {
            get {
                return ((string)(this["empresa_estado"]));
            }
            set {
                this["empresa_estado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool login_remember {
            get {
                return ((bool)(this["login_remember"]));
            }
            set {
                this["login_remember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_email {
            get {
                return ((string)(this["login_email"]));
            }
            set {
                this["login_email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_plan_recorrencia {
            get {
                return ((string)(this["user_plan_recorrencia"]));
            }
            set {
                this["user_plan_recorrencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vazio")]
        public string user_plan_fatura {
            get {
                return ((string)(this["user_plan_fatura"]));
            }
            set {
                this["user_plan_fatura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string empresa_nfe_ultnfe {
            get {
                return ((string)(this["empresa_nfe_ultnfe"]));
            }
            set {
                this["empresa_nfe_ultnfe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string empresa_nfe_serienfe {
            get {
                return ((string)(this["empresa_nfe_serienfe"]));
            }
            set {
                this["empresa_nfe_serienfe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int empresa_nfe_servidornfe {
            get {
                return ((int)(this["empresa_nfe_servidornfe"]));
            }
            set {
                this["empresa_nfe_servidornfe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string user_password {
            get {
                return ((string)(this["user_password"]));
            }
            set {
                this["user_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_cidade {
            get {
                return ((string)(this["empresa_cidade"]));
            }
            set {
                this["empresa_cidade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_ibge {
            get {
                return ((string)(this["empresa_ibge"]));
            }
            set {
                this["empresa_ibge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string empresa_crt {
            get {
                return ((string)(this["empresa_crt"]));
            }
            set {
                this["empresa_crt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_unique_id {
            get {
                return ((string)(this["empresa_unique_id"]));
            }
            set {
                this["empresa_unique_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int user_sub_user {
            get {
                return ((int)(this["user_sub_user"]));
            }
            set {
                this["user_sub_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int user_comissao {
            get {
                return ((int)(this["user_comissao"]));
            }
            set {
                this["user_comissao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user_dbhost {
            get {
                return ((string)(this["user_dbhost"]));
            }
            set {
                this["user_dbhost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_email {
            get {
                return ((string)(this["empresa_email"]));
            }
            set {
                this["empresa_email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int empresa_servidornfse {
            get {
                return ((int)(this["empresa_servidornfse"]));
            }
            set {
                this["empresa_servidornfse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_rps {
            get {
                return ((string)(this["empresa_rps"]));
            }
            set {
                this["empresa_rps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_serienfse {
            get {
                return ((string)(this["empresa_serienfse"]));
            }
            set {
                this["empresa_serienfse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_codigoitemnfse {
            get {
                return ((string)(this["empresa_codigoitemnfse"]));
            }
            set {
                this["empresa_codigoitemnfse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_codigotributacaonfse {
            get {
                return ((string)(this["empresa_codigotributacaonfse"]));
            }
            set {
                this["empresa_codigotributacaonfse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double empresa_aliquotanfse {
            get {
                return ((double)(this["empresa_aliquotanfse"]));
            }
            set {
                this["empresa_aliquotanfse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int empresa_calculanfse {
            get {
                return ((int)(this["empresa_calculanfse"]));
            }
            set {
                this["empresa_calculanfse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int empresa_issretido {
            get {
                return ((int)(this["empresa_issretido"]));
            }
            set {
                this["empresa_issretido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empresa_infadnfse {
            get {
                return ((string)(this["empresa_infadnfse"]));
            }
            set {
                this["empresa_infadnfse"] = value;
            }
        }
    }
}
