using Emiplus.Data.Core;
using Emiplus.Data.Helpers;
using SqlKata.Execution;
using System;
using System.IO;
using System.Linq;

namespace Emiplus.Data.Database
{
    class CreateTables
    {
        private QueryFactory dbLocal;
        private QueryFactory dbPdrao;

        private string _PathPadrao { get; set; }
        private string _PathLocal { get; set; }

        public CreateTables()
        {
            _PathPadrao = IniFile.Read("Path", "LOCAL") + @"\Update\PADRAO.fdb";
            _PathLocal = IniFile.Read("Path", "LOCAL") + @"\EMIPLUS.fdb";

            var connectPadrao = new Connect();
            connectPadrao.update = true;
            dbPdrao = connectPadrao.Open();

            var connectLocal = new Connect();
            connectPadrao.update = false;
            dbLocal = connectLocal.Open();
        }

        private void CreateGenerator(string trigger, string tabela, string generator)
        {

            dbLocal.Select("CREATE GENERATOR " + generator + ";");

            string s2;
            s2 = "CREATE TRIGGER " + trigger + " FOR " + tabela + " ";
            s2 = s2 + "ACTIVE BEFORE INSERT ";
            s2 = s2 + "POSITION 0 ";
            s2 = s2 + "AS ";
            s2 = s2 + "BEGIN ";
            s2 = s2 + "IF (NEW.ID IS NULL) THEN ";
            s2 = s2 + "NEW.ID = GEN_ID(" + generator + ", 1); ";
            s2 = s2 + "End";

            dbLocal.Select(s2);
        }

        public void CreateTable(string table)
        {
            dbLocal.Select("CREATE TABLE " + table + "(id integer generated by default as identity primary key); ");
        }

        public void CreateColumn(string table, string column, int type, int type_sub, int size)
        {
            string tipoCriar = "", tamanhoColuna = "";
            if (type == 16 && type_sub == 1)
            {
                tipoCriar = "NUMERIC(18,4)";
            }
            else if (type == 8)
            {
                //integer
                tipoCriar = "INTEGER";
            }
            else if (type == 12)
            {
                //date
                tipoCriar = "DATE";
            }
            else if (type == 13)
            {
                //time
                tipoCriar = "TIME";
            }
            else if (type == 35)
            {
                //timestamp
                tipoCriar = "TIMESTAMP";
            }
            else if (type == 37)
            {
                //varchar
                if (size == 0)
                {
                    tamanhoColuna = "255";
                }
                else
                {
                    tamanhoColuna = size.ToString();
                }

                tipoCriar = "VARCHAR(" + tamanhoColuna + ")";
            }

            dbLocal.Select("ALTER TABLE " + table + " ADD " + column + " " + tipoCriar + ";");
        }

        public void CheckTables()
        {
            if (!File.Exists(_PathPadrao))
            {
                return;
            }

            var data = dbPdrao.Select(@"SELECT
              R.RDB$RELATION_NAME as tabela,
              R.RDB$FIELD_NAME as coluna,
              R.RDB$FIELD_SOURCE,
              F.RDB$FIELD_LENGTH as tamanho,
              F.RDB$FIELD_TYPE as tipo,
              F.RDB$FIELD_SCALE,
              F.RDB$FIELD_SUB_TYPE as subtipo
            FROM
              RDB$RELATION_FIELDS R
              JOIN RDB$FIELDS F
                ON F.RDB$FIELD_NAME = R.RDB$FIELD_SOURCE
              JOIN RDB$RELATIONS RL
                ON RL.RDB$RELATION_NAME = R.RDB$RELATION_NAME
            WHERE
              COALESCE(R.RDB$SYSTEM_FLAG, 0) = 0
              AND
              COALESCE(RL.RDB$SYSTEM_FLAG, 0) = 0
              AND
              RL.RDB$VIEW_BLR IS NULL
            ORDER BY
              R.RDB$RELATION_NAME,
              R.RDB$FIELD_POSITION");
            foreach (var item in data)
            {
                string coluna = "", tabela = "";
                int tipo = 0, tamanho = 0, subtipo = 0;

                coluna = item.COLUNA.Trim();
                tabela = item.TABELA.Trim();
                tipo = item.TIPO;
                subtipo = item.SUBTIPO == null ? 0 : item.SUBTIPO;
                tamanho = item.TAMANHO;

                var localTabelas = dbLocal.Select(@"select f.rdb$relation_name as tabela, f.rdb$field_name as coluna
                    from rdb$relation_fields f
                    join rdb$relations r on f.rdb$relation_name = r.rdb$relation_name
                    and r.rdb$view_blr is null
                    and(r.rdb$system_flag is null or r.rdb$system_flag = 0)
                    WHERE f.rdb$relation_name = '" + tabela + "' order by 1, f.rdb$field_position;");

                if (localTabelas.Count() == 0)
                {
                    CreateTable(tabela);
                }

                var localColunas = dbLocal.Select(@"SELECT
              R.RDB$RELATION_NAME as tabela,
              R.RDB$FIELD_NAME as coluna,
              R.RDB$FIELD_SOURCE,
              F.RDB$FIELD_LENGTH as tamanho,
              F.RDB$FIELD_TYPE as tipo,
              F.RDB$FIELD_SCALE,
              F.RDB$FIELD_SUB_TYPE
            FROM
              RDB$RELATION_FIELDS R
              JOIN RDB$FIELDS F
                ON F.RDB$FIELD_NAME = R.RDB$FIELD_SOURCE
              JOIN RDB$RELATIONS RL
                ON RL.RDB$RELATION_NAME = R.RDB$RELATION_NAME
            WHERE
              COALESCE(R.RDB$SYSTEM_FLAG, 0) = 0
              AND
              COALESCE(RL.RDB$SYSTEM_FLAG, 0) = 0
              AND
              RL.RDB$VIEW_BLR IS NULL
              AND R.RDB$FIELD_NAME = '" + coluna + "' AND R.RDB$RELATION_NAME = '" + tabela + "' ORDER BY R.RDB$RELATION_NAME, R.RDB$FIELD_POSITION");
                if (localColunas.Count() == 0)
                {
                    CreateColumn(tabela, coluna, tipo, subtipo, tamanho);
                }
            }

            var padraoGenerators = dbPdrao.Select(@"SELECT RDB$GENERATOR_NAME as generator FROM Rdb$Generators WHERE RDB$GENERATOR_NAME like 'GEN_%';");
            foreach (var itemP in padraoGenerators)
            {
                var trigger = itemP.GENERATOR.Trim().Replace("GEN_", "").Replace("_ID", "");
                InsertGenerator(itemP.GENERATOR.Trim(), trigger);
            }
        }

        private void InsertGenerator(string generatorName, string triggerName)
        {
            var localGenerators = dbLocal.Select(@"SELECT RDB$GENERATOR_NAME as generator FROM Rdb$Generators WHERE RDB$GENERATOR_NAME like '" + generatorName + "';");
            if (localGenerators.Count() == 0)
            {
                var triggers = dbLocal.Select(@"select * from RDB$TRIGGERS where RDB$trigger_name like '%" + triggerName + "%'");

                if (triggers.Count() == 0)
                {
                    string generator = "", trigger = "", tabela = "";

                    generator = generatorName;

                    tabela = generator.Replace("_ID", "");
                    tabela = tabela.Replace("GEN_", "");

                    trigger = tabela + "_BI";

                    CreateGenerator(trigger, tabela, generator);

                }
            }
        }
    }
}
